### ISSUE TITLE
Unable to load due to missing native, despite having the supposed dependancy installed 

### ISSUE THREAD

**Issue by Kikio229** [1zc/SM-Discord-Chat#4]
L 02/27/2023 - 03:27:11: [SM] Unable to load plugin "Infra-DiscordChat.smx": Native "DiscordWebHook.Send" was not found

The Discord API plugin IS installed on my server and yet it still refuses to work.

**Comment by cavcavv** [comment]
My guess is this is due to some change in how the Discord API works.  I'm getting this same error.

**Comment by blackletum** [comment]
yup same

shame

**Comment by 1zc** [comment]
Sorry for the silence - to be clear, a lot of people don't face this problem which is why you see some recommending you download `discord_api.smx`, but I can see why this is insanely confusing now. There are way too many different "Discord API" plugins now, only some of which actually work with this, that's my bad: it should be on the README. Not sure why I didn't do that before, lol

This one should work: https://github.com/Cruze03/sourcemod-discord

**Comment by 1zc** [comment]
https://github.com/1zc/SM-Discord-Chat/commit/297603bba3bd09de719f0de66e0bf2995c71e6c6
